<?php
session_start();

function genPass($new)
{
    echo "PASSWORD AUTOGENERATED AS '{$new}': CHANGE BY EDITING AUTH_CODE.PHP";
    $txt = "<?php \$auth=\"{$new}\"; ?>"; // Compose the autogen'd auth_code.php
    $newPass = fopen("auth_code.php", "w");
    fwrite($newPass, $txt);
    fclose($newPass);
}

if (!include ('auth_code.php')) { // If there is no password file (sorry),
    $auth = "default";            // Generate one with a default password.
    genPass($auth);               // This probably sucks, BAD.
}

if (isset($_SESSION['authorized']) && $_SESSION['authorized'] == 1) {
    // Already authorized.
    header('Location: ./'); // Return to the editor
    exit;
}

if ($_POST['pass'] == $auth) { // Password is correct.
    $_SESSION['authorized'] = 1;
    header('Location: ./'); // Go to the editor
    exit;
} else { // Password is INCORRECT
    unset($_SESSION['authorized']); // Revoke session and post login form
    {?>
		<form method="POST" action="">
    	Pass <input type="password" name="pass"></input><br/>
    	<input type="submit" name="submit" value="Go"></input>
    	</form>
	<?php }
}
?>
